// <auto-generated />
using System;
using EnglishWordsBot.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishWordsBot.DAL.Migrations
{
    [DbContext(typeof(EnglishWordsBotDbContext))]
    [Migration("20260618090559_AddFileFieldsToWordInfo")]
    partial class AddFileFieldsToWordInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnglishWordsBot.DAL.Models.IntervalWordRepeatInfo", b =>
                {
                    b.Property<int>("WordInfoId")
                        .HasColumnType("int");

                    b.Property<int>("Repeatednterval")
                        .HasColumnType("int");

                    b.HasKey("WordInfoId");

                    b.HasIndex("Repeatednterval");

                    b.ToTable("IntervalWordRepeatInfos", (string)null);
                });

            modelBuilder.Entity("EnglishWordsBot.DAL.Models.WordInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("WordsInfo", (string)null);
                });

            modelBuilder.Entity("EnglishWordsBot.DAL.Models.IntervalWordRepeatInfo", b =>
                {
                    b.HasOne("EnglishWordsBot.DAL.Models.WordInfo", "WordInfo")
                        .WithOne()
                        .HasForeignKey("EnglishWordsBot.DAL.Models.IntervalWordRepeatInfo", "WordInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WordInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
